### ISSUE TITLE
Analyzer version in copy_with_extension_gen conflicts with mockito

### ISSUE THREAD

**Issue by NikoBoerger** [numen31337/copy_with_extension#31]
**Describe the issue**

There is a conflict in dependencies with the newest Mockito 5.0.0:

Because copy_with_extension_gen >=2.0.0-nullsafety.1 depends on analyzer ^0.41.2 and mockito 5.0.0 depends on analyzer ^1.0.0, copy_with_extension_gen >=2.0.0-nullsafety.1 is incompatible with mockito 5.0.0.

**Environment details**

Paste the flutter environment detail.
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 2.0.1, on macOS 11.2.2 20D80 darwin-x64, locale de-DE)
[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.3)
[✓] Xcode - develop for iOS and macOS
[✓] Chrome - develop for the web
[✓] Android Studio (version 4.1)
[✓] Connected device (1 available)

• No issues found!

Flutter 2.0.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision c5a4b4029c (23 hours ago) • 2021-03-04 09:47:48 -0800
Engine • revision 40441def69
Tools • Dart 2.12.0

```
dependencies:
  copy_with_extension: ^2.0.0-nullsafety.1
dev_dependencies:
  mockito: ^5.0.0
  copy_with_extension_gen: ^2.0.0-nullsafety.1
```

Could you please update the analyzer version in a new release? Thanks so much!
